name: Build and Push Docker Image to Gitea Registry

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        uses: docker/metadata-action@v5
        with:
          images: git.warp.ashwatdd.com/{{ env.GITEA_REPO_OWNER }}/{{ env.GITEA_REPO_NAME }}

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.apps-stash
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
