name: Build and Push Docker Image to Gitea Registry

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman and Buildah
        run: |
          sudo apt-get update -y
          sudo apt-get install -y podman buildah

      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.GITHUB_REPOSITORY }}
          tags: |
            ${{ env.GITHUB_REF_NAME }}
            ${{ env.GITEA_REF == 'refs/heads/main' && 'latest' || '' }}
          containerfiles: |
            ./Dockerfile

      - name: Podman Login to Gitea Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.GITHUB_SERVER_URL }}
          username: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Gitea Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.GITHUB_SERVER_URL }}
